---
- name: Configure motd (CentOS / Red Hat / Fedora)
  template:
    src: motd.j2
    dest: /etc/motd
  when: ansible_os_family == 'RedHat'

- name: Put SELinux in permissive mode (CentOS / Red Hat / Fedora)
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == 'RedHat' and not docker_testing