---
- name: Install Nginx repo file (CentOS / Red Hat / Fedora)
  copy:
    src: nginx.repo
    dest: "/etc/yum.repos.d/nginx.repo"
    owner: root
    group: root
  when: ansible_os_family == 'RedHat'

- name: Update system
  action: "{{ ansible_pkg_mgr }}"
  args:
    update_only: yes
    update_cache: yes

- name: Install Nginx
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: nginx
    state: latest

#- name: Install goaccess
#  action: "{{ ansible_pkg_mgr }}"
#  args:
#    name: goaccess
#    state: latest
#  when: epel_repofile_result.stat.exists