---
# tasks file for base role

- name: Assert supported distributions and versions for base role
  assert:
    that:
      - ( ansible_distribution == "RedHat" and ( ansible_distribution_major_version >= '8' )
        ) or
        ( ansible_distribution == "CentOS" and ( ansible_distribution_major_version >= '8' )
        ) or
        ( ansible_distribution == "Fedora" and ( ansible_distribution_major_version >= '30' )
        ) 

- name: Check if EPEL repo is already configured
  stat:
    path: "{{ epel_repofile_path }}"
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Fedora"
  register: epel_repofile_result

- name: Update and upgrade system
  action: "{{ ansible_pkg_mgr }}"
  args:
    update_only: yes
    update_cache: yes
  when: epel_repofile_result.stat.exists

- include: install.yml
- include: configure.yml