FROM docker.io/centos:latest

RUN dnf update -y && dnf install epel-release -y && dnf update -y

RUN dnf install znc znc-modtcl znc-modpython -y

RUN dnf clean all

RUN groupadd -g 960 znc && useradd -u 960 -D -h /znc -s /bin/sh -G znc znc

RUN mkdir -p /znc

WORKDIR /znc

EXPOSE 6697

USER znc

CMD ["znc", "--foreground", "--datadir", "/znc"]
