FROM docker.io/centos:latest

RUN dnf update -y && dnf install epel-release -y && dnf update -y

RUN dnf install znc znc-modtcl znc-modpython znc-clientbuffer -y

RUN dnf clean all

WORKDIR /

EXPOSE 6697

USER znc

CMD ["znc", "--foreground", "--datadir", "/etc/znc"]
