- name: Install docker engine
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: docker-ce
    state: latest

- name: Get ZNC image from autobuilder (Docker)
  command: docker pull docker.io/junland/jlab-znc
