variable "cpus" {
  type    = string
  default = "1"
}

variable "disk_size" {
  type    = string
  default = "25G"
}

variable "memory" {
  type    = string
  default = "1G"
}

variable "ssh_password" {
  type    = string
  default = "root"
}

variable "ssh_username" {
  type    = string
  default = "root"
}

variable "version" {
  type    = string
  default = "1.0.0"
}

source "qemu" "autogenerated_1" {
  accelerator      = "kvm"
  boot_command     = ["<up>e<wait><down><down><end><bs><bs><bs><bs><bs> text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos-kvm-ks.cfg <leftCtrlOn>x<leftCtrlOff><wait>"]
  boot_wait        = "10s"
  disk_interface   = "virtio"
  disk_size        = "${var.disk_size}"
  format           = "qcow2"
  headless         = true
  host_port_max    = 2229
  host_port_min    = 2222
  http_directory   = "http/centos"
  http_port_max    = 10089
  http_port_min    = 10082
  iso_checksum     = "sha256:562afe0c26df9673f168d64be2dfb0d24ce981e12b81db4171820af210e4cb7d"
  iso_url          = "http://yum.tamu.edu/centos/8-stream/isos/x86_64/CentOS-Stream-8-x86_64-20210506-boot.iso"
  net_device       = "virtio-net"
  output_directory = "centos-output"
  qemuargs         = [["-m", "${var.memory}"], ["-serial", "file:serial.out"], ["-smp", "cpus=${var.cpus}"], ["-bios", "/usr/share/ovmf/OVMF.fd"], ["-smbios", "type=0,uefi=on"]]
  shutdown_command = "shutdown -P now"
  ssh_password     = "${var.ssh_password}"
  ssh_port         = 22
  ssh_timeout      = "2400s"
  ssh_username     = "${var.ssh_username}"
  vm_name          = "centos-base-efi.qcow2"
}

build {
  sources = ["source.qemu.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["SSH_USERNAME=${var.ssh_username}", "SSH_PASSWORD=${var.ssh_password}"]
    pause_before     = "10s"
    scripts          = ["scripts/centos/00-base.sh"]
  }

  provisioner "shell" {
    environment_vars = ["SSH_USERNAME=${var.ssh_username}", "SSH_PASSWORD=${var.ssh_password}"]
    inline           = ["dnf install -y git qemu-img drpm && dnf clean all -y", "dnf remove -y --oldinstallonly --setopt installonly_limit=2 kernel || true"]
    pause_before     = "10s"
  }

}
