---
# defaults file for this role
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"

mon_ver: "0.18.1"