#!/bin/bash
# Original script by JKE (http://keihsler.com/redmine/projects/dw_os_cos7/wiki/Setup_motd)
# Adapted by John Unland (junland)

echo " >>> Generating MOTD..."

echo -e " 
*******************************************************************
* Version   = jlab Infrastructure OS, powered by `cat /etc/centos-release`
* Kernel    = `uname -r`
* Uptime    = `uptime | sed 's/.*up \([^,]*\), .*/\1/'`
* Mem /free = `cat /proc/meminfo | grep MemTotal | awk {'print $2'}` kB / `cat /proc/meminfo | grep MemFree | awk {'print $2'}` kB 
* last updt = `date`
*******************************************************************
" > /etc/motd

echo " >>> MOTD Generation completed..."
