FROM centos:latest

RUN mkdir /work

WORKDIR /work

RUN dnf update -y && dnf install epel-release -y && dnf install tree sudo ansible python3-libselinux -y

RUN dnf remove epel-release -y

RUN rm -rf /etc/*epel.repo

COPY ./ .

RUN mv ./test/test-playbook.yml ./

RUN ansible-playbook --become-user root test-playbook.yml

RUN ls -la /etc/nginx/sites-enabled

RUN cat /etc/motd