---
- name: Install Nginx repo file (CentOS / Red Hat / Fedora)
  copy:
    src: nginx.repo
    dest: "/etc/yum.repos.d/nginx.repo"
    owner: root
    group: root
  when: ansible_os_family == 'RedHat'

- name: Update system
  action: "{{ ansible_pkg_mgr }}"
  args:
    update_only: yes
    update_cache: yes

- name: Install Nginx
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: nginx
    state: latest
    
- name: Install goaccess deps (1/2)
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: GeoIP
    state: latest
    
- name: Install goaccess deps (2/2)
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: tokyocabinet
    state: latest

- name: Install goaccess
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/32/Everything/x86_64/os/Packages/g/goaccess-1.3-1.fc32.x86_64.rpm
    state: latest

- name: Install acme.sh
  command: curl https://get.acme.sh | sh